# Generated by Django 3.0.8 on 2020-07-11 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
    ]
