# Generated by Django 3.0.8 on 2020-07-11 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy_app', '0002_auto_20200711_0032'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
